version: '3'

services:
  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
