version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example__db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    image: tomcat:9.0
    container_name: tomcat_container
    ports:
      - "8080:8080"
    volumes:
      - ./target/Names.war:/usr/local/tomcat/webapps/root.war
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=example_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
